# Generated by Django 5.1.4 on 2025-01-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_remove_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
    ]
